server:
  port: 8085

spring:
  application:
    name: crm-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root12345
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: 'health,info,circuitbreakers'


spring.sleuth.enabled: true
spring.zipkin.enabled: true



resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 60s
        failureRateThreshold: 10
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.net.ConnectException  # 添加服务连接异常
    instances:
      itemService:
        baseConfig: default
      logisticsService:
        baseConfig: default
      paymentService:
        baseConfig: default
